#pragma once
#include "XELog.h"
#include "CPPThreadRunner.h"
#include "CPPLambdaRunner.h"
#include "SendKeyInput.h"
#include "SendMouseInput.h"
#include "Arithmetic.h"
#include "DelayManager.h"
#include "MapFunctions.h"
